### ISSUE TITLE
Verfication Program

### ISSUE THREAD

**Issue by marius-j-i** [Loevland/UiTHack24#76]
~~Hand out binary/source code that verifies if the input flag-guess is correct.~~
~~Use reverse engineering to narrow down flag by process of elimination.~~

Process that for some input verifies a flag as correct/not based on a set of polynomial equations with values from the flag.
Intended solution something in the field of constraint solvers, e.g., Z3 or angr.

**Comment by Loevland** [comment]
Tror "expired_license" oppgaven ligner på denne kanskje? 
Den tar flagget som input og "krypterer" det ,og gjør en sjekk mot det ordentlige flagget, og sier "Correct" eller "Incorrect" basert på om flagget er rett

**Comment by marius-j-i** [comment]
Writeup e ikke lagd for den, men e det sånn at du må bruke constraint solvers for oppgaven?
Hvis så blir den ganske lik, ja.

**Comment by Loevland** [comment]
E ikke intended at man må bruke constraint-solvers på "expired_license", så hvis den her oppgaven går ut på constraint-solving så e den ikke den samme

**Comment by marius-j-i** [comment]
Den ja/nei deln va delvis det æ så for mæ, men hadde løst å bli bedre med z3 / angr så tænke den heller kan fokusere dær.

**Comment by Loevland** [comment]
Ja/nei på om flagget e korrekt blir ganske naturlig imo å inkludere i en constraint-oppgave, så hvis d va initial plan så e d bare å gå for d du tenkte
