### ISSUE TITLE
A Key Still Needs A Chest

### ISSUE THREAD

**Issue by marius-j-i** [Loevland/UiTHack24#80]
Hand out an `id_rsa` or `id_ed25519` private key with the issue's title; that's it.
The challenge has an SSH host with this private key's public complement in its `~/.ssh/authorized_keys`.
The flag is in a clear-text file in the default starting directory.

The solution involves looking at the information contained in the private key via command:
```bash
cat id_ed25519|head -n -1|tail -n +2|base64 --decode
```
which will output something like:
> `openssh-key-v1nonenone3ssh-ed25519 '-t'G@*Kڑf36m~Assh-ed25519 '-t'G@*Kڑf36m~A@p)Dx?Ņ4@v'-t'G@*Kڑf36m~Akey-hole@chest.td.org.uit.no`

The clue is that the hostname for the remote machine is detailed at the end because the key was generated there and has the hostname as the computer-name. 
Access is established via:
```bash
ssh -i id_ed25519 key-hole@chest.td.org.uit.no
```

**Comment by Loevland** [comment]
Den her kreve vel at vi må spinne opp en ekstra maskin, for man kan vel ikke SSHe inn i Docker?

**Comment by marius-j-i** [comment]
Det va langs tankegangen, ja.
Så framt æ ser for mæ trængs det en DNS entry for `chest.td.org.uit.no` og en VM.
Men skjønne at barebones VM == $\infty$ crash management når arrangementet e underveis.

Har du vært borti måta å route ssh login til en docker container for et set med brukera?
E.g., `admin@dns.addr.no` går barebone VM, og `user@dns.addr.no` går til container instance.

**Comment by Loevland** [comment]
Litt usikker, så tror muligheitan burde sjekkes ut i så fall

**Comment by marius-j-i** [comment]
Seeer lovanes ut? 🤨 
https://phoenixnap.com/kb/how-to-ssh-into-docker-container

Eller e det kun lokalt den ip addressa man får for docker?

**Comment by Loevland** [comment]
Såvidt æ forstår artikkelen så e d vel bare sånn man kan ssh sæ inn i en docker-container fra maskina som hoste, men mulig man kanskje kan expose nokka porter for å få det til utenfra også (?). Har bare vært borti ssh til docker fra maskina som hoste containeren, men burde sikkert være mulig me nokka nettverksmagi å få d til å funke

**Comment by Loevland** [comment]
Meine å huske d va en CTF tidligere i høst som hadde SSH på en oppgave, men litt usikker på om de kjørte docker eller ikke. Kan prøve å leite litt og evt. kontakte dem etter Capstone e levert for å høre korsn dem gjorde d

**Comment by marius-j-i** [comment]
Æ fikk tel å bruke ssh lokalt for å få tilgang til container med ssh nøkkel.
Neste e vel om vi klare å eksponere containern på lurt vis.
Eller kan vi build'e et image som kan docker pull'es ned av deltagera?

**Comment by Loevland** [comment]
D går an å få dem til å måtte pulle et image for oppgaven, men hjelpe d nokka da?

**Comment by marius-j-i** [comment]
Tjaaa e det super lætt å få tak i ei fil inni et bygd image?

**Comment by Loevland** [comment]
Man har vel root access til containeren når man pulle og kjøre containeren, så burde vel bare være en docker exec for å få shell tror æ?

**Comment by marius-j-i** [comment]
Huh, så `CMD ["/usr/bin/sshd", "-D"]` stoppe ikke folk å starte en `/bin/bash` session?

**Comment by Loevland** [comment]
Ah okei, du har nokka measurements for d lagt inn i imaget? Da e æ ikke sikker på kor vanskelig d e, hvis den forhindre docker exec kommandoer

**Comment by Loevland** [comment]
Har forøvrig funnet oppgaven fra en CTF som æ tror løste d her problemet, så kan prøve å høre me dem korsn dem gjorde d hvis ikke den sshd greia funke

**Comment by marius-j-i** [comment]
Nvm, æ klarte å starte root session med image'et tilgjengelig lokalt.
